#!/bin/sh
#SBATCH --export=ALL
#SBATCH -p sq
#SBATCH --time=48:00:00
#SBATCH -A Research_Project-T109423
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=256
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=e.c.phelps@exeter.ac.uk
#SBATCH --output=gffread_new.out
#SBATCH --error=gffread_new.err
#SBATCH --job-name=gffread_new

#Set up anaconda environment with agat
PATH=~/anaconda3/bin/:$PATH
source activate agat #I've also installed gffread in this env

cd /lustre/home/ecp226/GuppyGenome2025

inpath=/lustre/home/ecp226/GuppyGenome2025/data/new/
outpath=/lustre/home/ecp226/GuppyGenome2025/output/new/

GFF=STAR_annot_v2.braker3.gff3
GENOME=STAR.chromosomes.release.fasta
gffread ${inpath}${GFF} -g ${inpath}${GENOME} -P -o ${GFF::-4}_stopflagged_gffread.gff
gffread ${inpath}${GFF} -g ${inpath}${GENOME} -V -B -o ${GFF::-4}_stopremov_gffread.gff
